import express from 'express';
import { signIn } from './admin-user/sign-in.mjs';
import { adsRouter } from './ads/ads.mjs';
import { varsRouter } from './app-vars/app-vars.mjs';
import { bannerRouter } from './banner/banner.mjs';
import { blockRouter } from './block/block.mjs';
import { categoryRouter } from './category/category.mjs';
import { congratulationRouter } from './congratulation/congratulation.mjs';
import { constantRouter } from './constants/constants.mjs';
import { districtRouter } from './district/district.mjs';
import { eventRouter } from './event/event.mjs';
import { holidayRouter } from './holiday/holiday.mjs';
import { htmlRouter } from './html/html.mjs';
import { productRouter } from './product/product.mjs';
import { pushRouter } from './push/push.mjs';
import { regionRouter } from './region/region.mjs';
import { subCategoryRouter } from './sub-category/sub-category.mjs';
import { userTypeRouter } from './user-type/user-type.mjs';
import { userRouter } from './user/user.mjs';

const router = express.Router();

router.post('/sign-in',signIn);
router.use('/category',categoryRouter);
router.use('/sub-category',subCategoryRouter);
router.use('/product',productRouter);
router.use('/banner',bannerRouter);
router.use('/user',userRouter);
router.use('/holiday',holidayRouter);
router.use('/congratulation',congratulationRouter);
router.use('/constant-page',constantRouter);
router.use('/user-type',userTypeRouter);
router.use('/region',regionRouter);
router.use('/district',districtRouter);
router.use('/vars',varsRouter);
router.use('/push',pushRouter);
router.use('/event',eventRouter);
router.use('/html',htmlRouter);
router.use('/ads',adsRouter);
router.use('/block',blockRouter);
export const adminRouter = router;